# Generated by Django 3.1.5 on 2021-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todohuman_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todohuman',
            name='job',
            field=models.CharField(choices=[('primary', '学生'), ('success', '社会人'), ('dark', '無職')], default='社会人', max_length=50),
        ),
    ]
