# Generated by Django 3.1.5 on 2021-01-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210125_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='todohuman',
            name='memo',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
